<?php

/**
 * Apache OSL-2
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Amazonpay;

interface AmazonpayConstants
{
    const ACCESS_KEY_ID = 'AMAZONPAY:ACCESS_KEY_ID';
    const CLIENT_ID = 'AMAZONPAY:CLIENT_ID';
    const SELLER_ID = 'AMAZONPAY:SELLER_ID';
    const SECRET_ACCESS_KEY = 'AMAZONPAY:SECRET_ACCESS_KEY';
    const CLIENT_SECRET = 'AMAZONPAY:CLIENT_SECRET';
    const SANDBOX = 'AMAZONPAY:SANDBOX';
    const REGION = 'AMAZONPAY:REGION';
    const STORE_NAME = 'AMAZONPAY:STORE_NAME';
    const ERROR_REPORT_LEVEL = 'AMAZONPAY:ERROR_REPORT_LEVEL';
    const CAPTURE_NOW = 'AMAZONPAY:CAPTURE_NOW';
    const AUTH_TRANSACTION_TIMEOUT = 'AMAZONPAY:AUTH_TRANSACTION_TIMEOUT';

    const PAYMENT_REJECT_ROUTE = 'AMAZONPAY:PAYMENT_REJECT_ROUTE';
    const WIDGET_SCRIPT_PATH = 'AMAZONPAY:WIDGET_SCRIPT_PATH';
    const WIDGET_SCRIPT_PATH_SANDBOX = 'AMAZONPAY:WIDGET_SCRIPT_PATH_SANDBOX';
    const WIDGET_POPUP_LOGIN = 'AMAZONPAY:WIDGET_POPUP_LOGIN';

    const WIDGET_BUTTON_TYPE = 'AMAZONPAY:WIDGET_BUTTON_TYPE';
    const WIDGET_BUTTON_COLOR = 'AMAZONPAY:WIDGET_BUTTON_COLOR';
    const WIDGET_BUTTON_SIZE = 'AMAZONPAY:WIDGET_BUTTON_SIZE';

    const PAYMENT_METHOD = 'AMAZONPAY:PAYMENT_METHOD';
}
